// Generated by CoffeeScript 1.3.3
(function() {

  window.App = {
    years: {},
    init: function() {
      var _this = this;
      return $.ajax('data.json').done(function(response) {
        var lines, year, _results;
        _this.years = new App.Years();
        _results = [];
        for (year in response) {
          lines = response[year];
          _results.push(_this.years.add(new App.Year(lines, year)));
        }
        return _results;
      });
    }
  };

}).call(this);
