// Generated by CoffeeScript 1.3.3
(function() {

  App.Years = (function() {

    function Years() {
      this.years = [];
    }

    Years.prototype.add = function(year) {
      return this.years.push(year);
    };

    Years.prototype.getWeekly = function(idx) {};

    return Years;

  })();

}).call(this);
