// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.Years = (function() {

    function Years() {
      this.years = [];
    }

    Years.prototype.add = function(year) {
      return this.years.push(year);
    };

    return Years;

  })();

  App.Year = (function(_super) {

    __extends(Year, _super);

    function Year(dailyData, year) {
      var currentDate, day, days, _i, _len, _ref;
      this.dailyData = dailyData;
      this.year = year;
      this.weeklyData = {};
      _ref = this.dailyData;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        days = _ref[_i];
        day = days.shift().split('-');
        currentDate = new Date(day[0], day[1] - 1, day[2]);
        if (this.weeklyData[currentDate.getWeek()]) {
          this.weeklyData[currentDate.getWeek()] = this.weeklyData[currentDate.getWeek()].sumWith(days);
        } else {
          this.weeklyData[currentDate.getWeek()] = days;
        }
      }
    }

    Year.prototype.getYear = function() {
      return this.year;
    };

    Year.prototype.getDaily = function(idx) {
      return this.dailyData[idx];
    };

    Year.prototype.getWeekly = function(idx) {
      return this.weeklyData[idx];
    };

    return Year;

  })(Backbone.Model);

}).call(this);
